migration:
  create_province_table:
    fields: |
      country_id:integer:notNull:foreignKey(country),
      code:string(50),
      name:string(255),
      abbreviation:string(255)
  create_zone_group_table:
    fields: |
      zone_code:string(50):notNull:foreignKey(zone code),
      type:string(50),
      group_code:string(50)
model:
  zone_group:
  province:
crud:
  province:
    modelClass: codexten\yii\modules\geo\models\Province
